import { describe, expect, it } from "vitest";
import snapshotFixture from "./fixtures/snapshot.json";
import patchFixture from "./fixtures/patch.json";

// The fixtures are generated by tests/protocol_fixtures.rs. If Rust changes the
// wire format, that test fails; if this model has not caught up, this one does.

describe("the wire model matches what Rust produces", () => {
  it("parses a snapshot", () => {
    const message = snapshotFixture;
    expect(message.type).toBe("snapshot");

    const node = message.nodes.at(0);
    const job = message.jobs.at(0);
    if (!node || !job) throw new Error("snapshot fixture is empty");

    expect(node.display_name).toBe("Database Committer");
    expect(node.kind).toBe("sink");
    expect(node.counters.p95_ms).toBe(310);
    expect(job.phase).toBe("held");
    expect(job.reason).toContain("finality");
    expect(job.meta.tx_count).toBe("142");
    expect(message.process?.cpu_pct).toBe(12.4);
  });

  it("parses a patch", () => {
    const patch = patchFixture;
    expect(patch.type).toBe("patch");
    expect(patch.removed_jobs).toEqual(["2049101"]);
    expect(patch.dropped_events).toBe(7);
    expect(patch.process).toBeNull();
  });
});
