import { describe, expect, it } from "vitest";
import snapshotFixture from "./fixtures/snapshot.json";
import patchFixture from "./fixtures/patch.json";
import type { Patch, ServerMessage, Snapshot } from "./types";

// The fixtures are generated by tests/protocol_fixtures.rs. If Rust changes the
// wire format, that test fails; if this model has not caught up, this one does.

describe("the wire model matches what Rust produces", () => {
  it("parses a snapshot", () => {
    const message = snapshotFixture as ServerMessage;
    expect(message.type).toBe("snapshot");

    const snapshot = message as Snapshot;
    expect(snapshot.nodes[0].display_name).toBe("Database Committer");
    expect(snapshot.nodes[0].kind).toBe("sink");
    expect(snapshot.nodes[0].counters.p95_ms).toBe(310);
    expect(snapshot.jobs[0].phase).toBe("held");
    if (snapshot.jobs[0].phase === "held") {
      expect(snapshot.jobs[0].reason).toContain("finality");
    }
    expect(snapshot.jobs[0].meta.tx_count).toBe("142");
    expect(snapshot.process?.cpu_pct).toBe(12.4);
  });

  it("parses a patch", () => {
    const patch = patchFixture as unknown as Patch;
    expect(patch.type).toBe("patch");
    expect(patch.removed_jobs).toEqual(["2049101"]);
    expect(patch.dropped_events).toBe(7);
    expect(patch.process).toBeNull();
  });
});
